[theme]
# Primary accent color for interactive elements.
primaryColor = "#1a73e8"  # A modern blue

# Background color for the main content area.
backgroundColor = "#f0f2f5" # A light grey, common for feeds

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor = "#ffffff" # White

# Color used for almost all text.
textColor = "#050505" # Near-black for readability

# Font family for all text in the app.
font = "sans serif"
